Added Cobertura XML coverage support
Codeception/Codeception pull request #5994
Opened 2020-10-06 15:43 UTC by zachkknowbe4

Now that PHPUnit has support for Cobertura XML, I've added support so that Codeception can make use of it.

2020-10-07 16:28 UTC, Naktibalda requested changes

2020-10-07 16:28 UTC, Naktibalda commented on src/Codeception/Coverage/Subscriber/Printer.php
> +        $writer = new \SebastianBergmann\CodeCoverage\Report\Cobertura;
Please check if this class is defined before using it and throw exception that php-code-coverage >=9.2.0 is required.

2020-10-07 16:28 UTC, Naktibalda commented on tests/coverage/RemoteWithCoberturaCept.php
> +$I->wantTo('try generate remote cobertura xml report');
This test fails with PHPUnit 8 and older so it must be skipped if `\SebastianBergmann\CodeCoverage\Report\Cobertura` class does not exist.

Please check if this code works:
```php
if (!class_exists(\SebastianBergmann\CodeCoverage\Report\Cobertura::class)) {
  $scenario->skip('Cobertura report requires php-code-coverage 9.2');
}
````

2020-10-07 16:38 UTC, Naktibalda commented
Also please document your new parameter in the docblock of Run command: https://github.com/Codeception/Codeception/blob/4.1/src/Codeception/Command/Run.php#L74-L77

It is used to generate this reference page: https://codeception.com/docs/reference/Commands#Run

2020-10-09 16:43 UTC, Naktibalda approved these changes
Looks good now.

2020-10-09 17:28 UTC, zachkknowbe4 commented
Awesome thank you.

2020-10-11 17:35 UTC, merged