Add actor to Cest tests dataProviders
Codeception/Codeception pull request #6696
Opened 2023-10-02 14:37 UTC by weeg

It makes possible to use actors inside dataProviders. It's a very useful functionality, during testing it happens that data need to be retrieved ie.: from the database, but it's not possible to use it with the current solution. There was a discussion about it in the past: #4087 

I am not sure if I implemented it in the correct way, I am new to Codeception and open source contribution as well. What do you think of it @DavertMik?

2023-10-02 15:52 UTC, Arhell approved these changes

2023-10-10 18:23 UTC, DavertMik requested changes
@weeg Thanks for the PR
I like it in general and I have some ideas to improve it
Please tell what you think

2023-10-10 18:23 UTC, DavertMik commented on src/Codeception/Command/Shared/ActorTrait.php
> +    protected function getActor(): ?string
I would expect this function to actually return an Actor
Can we rename it to `getActorClassName`

2023-10-10 18:23 UTC, DavertMik commented on src/Codeception/Command/Shared/ActorTrait.php
> +    }
Method `getActor` can also be implemented here:

```php
private function getActor($test) 
{
    $actorClass = $this->getActor();
    return $actorClass ? new $actorClass(new Scenario($test)) : null;
}
```

2023-10-10 18:23 UTC, DavertMik commented on src/Codeception/Test/Loader/Cest.php
> +                $actorClass = $this->getActor();
```suggestion
                $I = $this->getActor($test);
```

2023-12-03 07:17 UTC, W0rma commented
@DavertMik @Naktibalda Are you okay with the latest changes in this PR?

Seems like the author addressed all comments with the latest commit.

2023-12-22 19:21 UTC, merged

2023-12-22 19:22 UTC, Naktibalda commented
@weeg @W0rma @DavertMik Could someone document this new feature somewhere?

https://github.com/Codeception/codeception.github.com/tree/master/docs