Simplify command classes
Codeception/Codeception pull request #6750
Opened 2024-04-01 05:17 UTC by TavoNiievez

221 additions, 476 deletions.

2024-05-16 17:04 UTC, Naktibalda requested changes

2024-05-16 17:53 UTC, TavoNiievez commented on src/Codeception/Command/GenerateGroup.php
>          return 'Generates Group subscriber';
Done ✅

2024-05-16 18:14 UTC, TavoNiievez commented
@Naktibalda FYI, this is supposed to be the first of several PR's and I'm supposed to follow up with the other folders inside src/, I don't know how long that's going to take me, so you can take that into account when releasing 5.2 or not.

2024-07-23 06:22 UTC, Naktibalda approved these changes

2024-07-23 13:17 UTC, merged